#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["pygeomag==1.1.0"]
# ///
"""Generate the magnetic declination table in `src/magnetic.rs` from the World Magnetic Model.

    uv run tools/declination.py                     regenerate at the model and epoch it names
    uv run tools/declination.py --model WMM_2025 --epoch 2027.5   regenerate at another
    uv run tools/declination.py --check             fail if the table is not what it generates
    uv run tools/declination.py --drift [--at Y] [log.csv ...]   is the table stale?
    uv run tools/declination.py --px4 <checkout>    rebuild PX4's table, to check the generator
    python3 tools/declination.py --self-test        run the fixtures

The table is the model's declination every 10 degrees of latitude and longitude, at sea level, at
one epoch, in hundredths of a degree. The model is NCEI's coefficient file as `pygeomag` ships it,
checked against the sha256 below (`reference/README.md` records where NCEI publishes it); the
WMM is public domain, so the table carries no licence. The lines between the two marker comments
in `src/magnetic.rs` are this script's output and nothing else, and a run with no arguments reads
the model and epoch back from them, so regenerating at the same epoch leaves the file
byte-identical and `--check` says whether it does.

`--px4` is the evidence the generator is right: WMM-2020 at the epoch and scale PX4's
`geo_magnetic_tables.hpp` names reproduces PX4's `declination_table` cell for cell, a table PX4
built from NOAA's web calculator rather than from this code. A sign, an axis order or a unit
wrong here fails it. It also checks the converter's copy of PX4's table against the header.

`--drift` is when to regenerate (GOALS.md, "Magnetic declination from a table"). It prints, in
degrees, the table's largest difference from the model:

    interp_max     at the sites, at the table's epoch: the 10-degree grid's own error
    now_max        at the sites, at `--at` or today
    end_max        at the sites, at the end of the model's five-year life
    world_now_max  at every grid point within 60 degrees of the equator, at `--at` or today,
    world_end_max  and at the end of the model's life: the epoch's error where no site samples it

The sites are each `# Navigation origin` in the converted logs named, by default the corpus
(`data/logs/*.csv`) and INSANE's sequences (`target/insane/*.csv`), counted apart so a missing
set shows. `rust_max` is this script's lookup against the `declination_model=` the replay harness
pinned for each corpus log in `data/manifest.txt`, the Rust lookup at the same origin: past the
pins' rounding the two lookups have diverged, or the manifest predates the table, and the run
refuses.
"""

import argparse
import glob
import hashlib
import os
import re
import sys
import tempfile
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "src", "magnetic.rs")
MANIFEST = os.path.join(ROOT, "data", "manifest.txt")
CONVERTER = os.path.join(ROOT, "tools", "ulog2replay.py")
CORPUS = os.path.join(ROOT, "data", "logs", "*.csv")
INSANE = os.path.join(ROOT, "target", "insane", "*.csv")

RESOLUTION = 10
LATITUDES = range(-90, 91, RESOLUTION)
LONGITUDES = range(-180, 181, RESOLUTION)

# Degrees per table unit. Fixed rather than fitted to the table's extreme, as PX4's generator does:
# 180 degrees is 18000, inside i16, and a round unit is one a reader can check by eye.
SCALE = 0.01

# The latitude band `world_*` reads. Past it the declination turns fast enough near the magnetic
# poles that a 10-degree grid is no description of it at any epoch.
WORLD_BAND = 60

# `declination_model=` is printed to two decimals: half a unit, and f32 against f64 beside it.
PIN_TOLERANCE = 0.006

# sha256 of each coefficient file this script will build from, as `pygeomag` ships it. WMM_2025's
# is that of `WMM2025.COF` in NCEI's `WMM2025COF.zip`; WMM_2020 is here for `--px4` alone.
COEFFICIENTS = {
    "WMM_2025": "dfa8597825af4e0b87ff4198a5b4fb661b3c49f4cd090cd0164e0259b075582f",
    "WMM_2020": "e65453b7d2ed34ae30f6f7361aaec403e103c2abf59ee46393bd4c4f880c4fa8",
}

BEGIN = "// BEGIN generated by tools/declination.py; edit the script, not these lines."
END = "// END generated by tools/declination.py"
PROVENANCE = re.compile(r"`(WMM_\d{4})` at epoch (\d{4}\.\d+)")


def model(name):
    """A `pygeomag.GeoMag` for one coefficient file, refused unless its sha256 is the pinned one."""
    if name not in COEFFICIENTS:
        raise ValueError(f"no pinned coefficient file for {name}; known: {', '.join(COEFFICIENTS)}")
    import pygeomag

    path = os.path.join(os.path.dirname(pygeomag.__file__), "wmm", f"{name}.COF")
    with open(path, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    if digest != COEFFICIENTS[name]:
        raise ValueError(f"{path} has sha256 {digest}, not the pinned {COEFFICIENTS[name]}")
    return pygeomag.GeoMag(coefficients_file=f"wmm/{name}.COF")


def declination(geomag, latitude, longitude, epoch):
    """The model's declination in degrees, at sea level. Past the model's life only for `--px4`,
    whose epoch PX4 chose, and `--drift`, which asks how stale the table has become."""
    return geomag.calculate(glat=latitude, glon=longitude, alt=0, time=epoch,
                            allow_date_outside_lifespan=True).d


def end_of(name):
    """The last year of a model's five-year life: WMM_2025 runs to 2030."""
    return float(name.split("_")[1]) + 5.0


def epoch_of(text):
    """An epoch as the generated region writes it, so `PROVENANCE` reads it back: `2032` is
    `2032.0`."""
    return str(float(text))


def grid(geomag, epoch, scale):
    """The table: rows latitude -90 to 90, columns longitude -180 to 180, in units of `scale`."""
    rows = [[round(declination(geomag, lat, lon, epoch) / scale) for lon in LONGITUDES]
            for lat in LATITUDES]
    for row in rows:
        for value in row:
            if not -32768 <= value <= 32767:
                raise ValueError(f"{value} does not fit an i16 at scale {scale}")
    return rows


def wrap(values, indent, width=100):
    """Comma-separated values filling lines of at most `width` columns. The table sits under
    `#[rustfmt::skip]`, so this is the layout rather than a copy of rustfmt's."""
    lines, line = [], indent
    for i, value in enumerate(values):
        item = str(value) + ("," if i < len(values) - 1 else "")
        candidate = item if line == indent else " " + item
        if line != indent and len(line) + len(candidate) > width:
            lines.append(line)
            line, candidate = indent, item
        line += candidate
    lines.append(line)
    return lines


def rust(name, epoch, rows):
    """The generated region of `src/magnetic.rs`, markers included."""
    out = [
        BEGIN,
        "",
        "/// Degrees per table unit.",
        f"const SCALE: f32 = {SCALE};",
        "",
        "/// Grid spacing in degrees, on both axes.",
        f"const RESOLUTION: f32 = {RESOLUTION:.1f};",
        "",
        f"/// The declination from `{name}` at epoch {epoch}, at sea level, in [`SCALE`] degrees.",
        "/// Rows are latitude −90° to 90°, columns longitude −180° to 180°.",
        "#[rustfmt::skip]",
        f"const TABLE: [[i16; {len(LONGITUDES)}]; {len(LATITUDES)}] = [",
    ]
    for latitude, row in zip(LATITUDES, rows):
        out += [f"    // {latitude}°", "    ["] + wrap(row, " " * 8) + ["    ],"]
    out += ["];", "", END]
    return "\n".join(out)


def region(text):
    """(before, generated, after) of a file holding exactly one generated region."""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("want exactly one BEGIN and one END marker")
    before, rest = text.split(BEGIN)
    generated, after = rest.split(END)
    return before, BEGIN + generated + END, after


def provenance(generated):
    """(model, epoch) as the generated region names them."""
    found = PROVENANCE.findall(generated)
    if len(found) != 1:
        raise ValueError("the generated region names no single model and epoch")
    return found[0][0], found[0][1]


def table_of(generated):
    """The rows of a generated region, read back as integers."""
    body = generated.split("const TABLE", 1)[1].split("= [", 1)[1]
    rows = []
    for block in body.split("    [")[1:]:
        cells = block.split("    ],")[0]
        rows.append([int(v) for v in re.findall(r"-?\d+", cells)])
    if len(rows) != len(LATITUDES) or any(len(r) != len(LONGITUDES) for r in rows):
        raise ValueError(f"table is not {len(LATITUDES)} x {len(LONGITUDES)}")
    return rows


def lookup(rows, scale, latitude, longitude):
    """`declination_at` in `src/magnetic.rs`, in f64: bilinear in the cell about the point, each
    corner taken within half a turn of the south-west one."""
    latitude = min(max(latitude, -90.0), 90.0)
    if longitude > 180.0:
        longitude -= 360.0
    if longitude < -180.0:
        longitude += 360.0
    longitude = min(max(longitude, -180.0), 180.0)

    def cell(offset, count):
        index = min(int(offset / RESOLUTION), count - 2)
        return index, min(max(offset / RESOLUTION - index, 0.0), 1.0)

    row, north_frac = cell(latitude + 90.0, len(rows))
    column, east_frac = cell(longitude + 180.0, len(rows[0]))
    turn = 360.0 / scale
    sw = rows[row][column]

    def near_sw(value):
        return sw + (value - sw + turn / 2) % turn - turn / 2

    se = near_sw(rows[row][column + 1])
    nw, ne = near_sw(rows[row + 1][column]), near_sw(rows[row + 1][column + 1])
    south = sw + east_frac * (se - sw)
    north = nw + east_frac * (ne - nw)
    return difference((south + north_frac * (north - south)) * scale, 0.0)


def origins(paths):
    """(path, latitude, longitude) of each converted log's `# Navigation origin`, read from the
    header only, where it has one."""
    found = []
    for path in paths:
        with open(path) as f:
            for line in f:
                if not line.startswith("#"):
                    break
                m = re.match(r"# Navigation origin (-?[\d.]+) (-?[\d.]+) ", line)
                if m:
                    found.append((path, float(m.group(1)), float(m.group(2))))
    return found


def converted(pattern):
    """The replay inputs a glob matches, leaving out the harness's outputs and truth files."""
    return [p for p in sorted(glob.glob(pattern))
            if not re.search(r"\.(replay|raw|truth|px4|off)\b", os.path.basename(p))]


def pins(manifest):
    """`declination_model=` per log id, from the manifest's entry lines, where it is a number."""
    found = {}
    for line in manifest.splitlines():
        fields = line.split()
        if line.startswith("#") or len(fields) < 2 or not fields[1].endswith(".ulg"):
            continue
        m = re.search(r"(?<= )declination_model=(-?[\d.]+)(?= |$)", line)
        if m:
            found[fields[1][:-4]] = float(m.group(1))
    return found


def decimal_year(day):
    start = date(day.year, 1, 1)
    return day.year + (day - start).days / (date(day.year + 1, 1, 1) - start).days


def difference(a, b):
    """a - b in degrees, wrapped into [-180, 180)."""
    return (a - b + 180.0) % 360.0 - 180.0


def drift_figures(rows, sites, model_at, epoch, at, end):
    """The `--drift` maxima, from `model_at(latitude, longitude, year)` in degrees."""
    def worst(points, when):
        return max(abs(difference(value, model_at(lat, lon, when))) for lat, lon, value in points)

    at_sites = [(lat, lon, lookup(rows, SCALE, lat, lon)) for _, lat, lon in sites]
    nodes = [(lat, lon, rows[i][j] * SCALE) for i, lat in enumerate(LATITUDES)
             for j, lon in enumerate(LONGITUDES) if abs(lat) <= WORLD_BAND]
    return {
        "interp_max": worst(at_sites, epoch),
        "now_max": worst(at_sites, at),
        "end_max": worst(at_sites, end),
        "world_now_max": worst(nodes, at),
        "world_end_max": worst(nodes, end),
    }


def rust_agreement(rows, sites, pinned):
    """The largest |lookup - declination_model=| over the sites the manifest pins."""
    gaps = [abs(difference(lookup(rows, SCALE, lat, lon), pinned[log]))
            for path, lat, lon in sites
            if (log := os.path.basename(path).split(".")[0]) in pinned]
    return max(gaps) if gaps else None


def converter_table(text):
    """The rows of `DECLINATION_TABLE` in `tools/ulog2replay.py`."""
    body = text.split("DECLINATION_TABLE = (", 1)[1].split("\n)", 1)[0]
    return [[int(v) for v in re.findall(r"-?\d+", line)]
            for line in body.splitlines() if line.strip().startswith("(")]


def current():
    with open(TARGET) as f:
        text = f.read()
    return (text,) + region(text)


def regenerate(name, epoch, check):
    text, before, generated, after = current()
    if name is None:
        name, epoch = provenance(generated)
    epoch = epoch_of(epoch)
    rendered = before + rust(name, epoch, grid(model(name), float(epoch), SCALE)) + after
    if check:
        if rendered != text:
            sys.exit(f"declination: {TARGET} is not what {name} at epoch {epoch} generates; "
                     "run tools/declination.py")
        print(f"declination: {TARGET} is {name} at epoch {epoch}")
        return
    with open(TARGET, "w") as f:
        f.write(rendered)
    print(f"declination: {TARGET} from {name} at epoch {epoch}")


def px4(checkout):
    path = os.path.join(checkout, "src/lib/world_magnetic_model/geo_magnetic_tables.hpp")
    with open(path) as f:
        header = f.read()
    section = header.split("declination_table[")[0].rsplit("// Magnetic declination", 1)[1]
    name = re.search(r"Model: (WMM-\d{4})", section).group(1).replace("-", "_")
    epoch = float(re.search(r"Date: ([\d.]+)", section).group(1))
    scale = float(re.search(r"WMM_DECLINATION_SCALE_TO_DEGREES = ([\d.]+)f", header).group(1))
    body = header.split("declination_table[")[1].split("};")[0]
    want = [[int(v) for v in re.findall(r"-?\d+", line.split("*/")[1])]
            for line in body.splitlines() if "LAT:" in line]
    got = grid(model(name), epoch, scale)
    cells = [(lat, lon, g, w) for lat, gr, wr in zip(LATITUDES, got, want)
             for lon, g, w in zip(LONGITUDES, gr, wr) if g != w]
    with open(CONVERTER) as f:
        copy = "match" if converter_table(f.read()) == want else "differs"
    count = len(LATITUDES) * len(LONGITUDES)
    print(f"px4 model={name} epoch={epoch} scale={scale} cells={count} differ={len(cells)} "
          f"converter={copy}")
    for lat, lon, g, w in cells[:10]:
        print(f"  {lat} {lon}: {g} against PX4's {w}")
    if cells or copy != "match":
        sys.exit(1)


def drift(at, paths):
    _, _, generated, _ = current()
    name, epoch = provenance(generated)
    rows = table_of(generated)
    if paths:
        sets = {"named": origins(paths)}
    else:
        sets = {"corpus": origins(converted(CORPUS)), "insane": origins(converted(INSANE))}
    sites = [site for found in sets.values() for site in found]
    if not sites:
        sys.exit("declination: no `# Navigation origin` in the logs; fetch and convert first")
    geomag = model(name)
    figures = drift_figures(rows, sites, lambda lat, lon, when: declination(geomag, lat, lon, when),
                            float(epoch), at, end_of(name))
    with open(MANIFEST) as f:
        agreement = rust_agreement(rows, sites, pins(f.read()))
    counts = " ".join(f"{key}={len(found)}" for key, found in sets.items())
    values = " ".join(f"{key}={value:.2f}" for key, value in figures.items())
    rust_max = "none" if agreement is None else f"{agreement:.4f}"
    print(f"drift model={name} epoch={epoch} at={at:.2f} end={end_of(name):.1f} {counts} "
          f"{values} rust_max={rust_max}")
    if agreement is not None and agreement > PIN_TOLERANCE:
        sys.exit(f"declination: the lookup is {agreement:.4f} deg from a declination_model= pin; "
                 "re-pin data/manifest.txt after regenerating, or the two lookups have diverged")


def self_test():
    failures = []

    def check(name, got, want):
        if got != want:
            failures.append(f"{name}: got {got!r}, want {want!r}")

    def refused(name, call):
        try:
            call()
            failures.append(f"{name}: accepted")
        except ValueError:
            pass

    # A fake grid whose value is 100 * row + column, so the corner a lookup reads is legible.
    rows = [[100 * i + j for j in range(len(LONGITUDES))] for i in range(len(LATITUDES))]
    text = "head\n" + rust("WMM_2025", "2027.5", rows) + "\ntail\n"
    before, generated, after = region(text)
    check("region before", before, "head\n")
    check("region after", after, "\ntail\n")
    check("provenance", provenance(generated), ("WMM_2025", "2027.5"))
    # The next regeneration's natural spelling: an epoch written without a fraction still reads
    # back, since it is written through `epoch_of`.
    check("integer epoch", provenance(rust("WMM_2030", epoch_of("2032"), rows)),
          ("WMM_2030", "2032.0"))
    check("epoch unchanged", epoch_of("2027.5"), "2027.5")
    # Survives a reader that drops the first or last cell of a row, or a row: the read-back is
    # compared whole against the grid it was written from.
    check("read back", table_of(generated), rows)
    check("round trip", rust("WMM_2025", "2027.5", table_of(generated)), generated)
    # Unpacking the split refuses both of these too, so removing the count check survives
    # them: it is there for the message.
    refused("two regions", lambda: region(text + text))
    refused("no region", lambda: region("nothing"))
    short = generated.replace("        0, 1, 2,", "        1, 2,", 1)
    refused("a short row", lambda: table_of(short))

    # Wrapping: no line past 100 columns, a full line before the break, no comma on the last.
    values = list(range(-20000, -19963))
    lines = wrap(values, " " * 8)
    first = len(re.findall(r"-?\d+", lines[0]))
    check("wrap width", max(len(line) for line in lines) <= 100, True)
    check("wrap full", len(f"{lines[0]} {values[first]},") > 100, True)
    check("wrap last comma", lines[-1].endswith(","), False)
    check("wrap all values", sum(len(re.findall(r"-?\d+", line)) for line in lines), 37)

    # The lookup, against corners chosen to tell rows from columns. At (-90, -180) the cell's
    # south-west corner is 0; one step north is 100, one step east 1.
    check("corner", lookup(rows, 1.0, -90.0, -180.0), 0.0)
    check("north", lookup(rows, 1.0, -80.0, -180.0), 100.0)
    check("east", lookup(rows, 1.0, -90.0, -170.0), 1.0)
    check("inside", lookup(rows, 1.0, -85.0, -177.5), 50.25)
    check("last row and column", round(lookup(rows, 0.1, 90.0, 180.0), 6), -176.4)
    check("wraps", lookup(rows, 1.0, 0.0, 190.0), lookup(rows, 1.0, 0.0, -170.0))
    check("clamps", lookup(rows, 1.0, 95.0, 20.0), lookup(rows, 1.0, 90.0, 20.0))
    check("scale", lookup(rows, 0.01, -80.0, -180.0), 1.0)
    # Across the turn: 179 and -179 are two degrees apart, so halfway between them is 180, not
    # the 0 a plain average gives. Both orders, so a one-sided unwrap fails one of them.
    jump = [[0] * len(LONGITUDES) for _ in LATITUDES]
    jump[0][0], jump[0][1], jump[1][0], jump[1][1] = 17900, -17900, 17900, -17900
    check("across the turn east", round(abs(lookup(jump, 0.01, -90.0, -175.0)), 6), 180.0)
    jump[0][0], jump[0][1], jump[1][0], jump[1][1] = -17900, 17900, -17900, 17900
    check("across the turn west", round(abs(lookup(jump, 0.01, -90.0, -175.0)), 6), 180.0)
    jump[0][0], jump[0][1], jump[1][0], jump[1][1] = 17000, 17000, -17000, -17000
    check("across the turn north", round(abs(lookup(jump, 0.01, -85.0, -180.0)), 6), 180.0)

    check("difference wraps", difference(179.0, -179.0), -2.0)
    check("decimal year", decimal_year(date(2027, 7, 2)), 2027 + 182 / 365)
    check("end of life", end_of("WMM_2025"), 2030.0)
    refused("an unpinned model", lambda: model("WMM_1990"))

    # Origins come from the header alone, latitude first: a data row ends it, so an origin line
    # after one is not read (a scan that continued past the header would find it).
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "abc.csv")
        with open(path, "w") as f:
            f.write("# Converted from x\n# Navigation origin 10.5 -20.25 3.0 (lat deg, ...)\n"
                    "t,ax\n# Navigation origin 1.0 2.0 3.0 (late)\n")
        check("origins", origins([path]), [(path, 10.5, -20.25)])
        for name in ["abc.csv.replay.csv", "abc.raw.csv", "abc.truth.csv", "abc.px4.fusion.csv"]:
            open(os.path.join(tmp, name), "w").close()
        check("converted", converted(os.path.join(tmp, "*.csv")), [path])

    # Drift against a model that is 0.5 at the epoch, 1.5 at `at`, 3.0 at the end, on a flat
    # table of 0: each key reads its own year, and the larger of two sites. The second site's
    # model sits further away, so a `min` reads the first.
    flat = [[0] * len(LONGITUDES) for _ in LATITUDES]
    years = {2027.5: 0.5, 2026.0: 1.5, 2030.0: 3.0}
    sites = [("a.csv", 10.0, 10.0), ("b.csv", 20.0, 20.0)]
    figures = drift_figures(flat, sites, lambda lat, lon, when: years[when] * (1 + lat / 10),
                            2027.5, 2026.0, 2030.0)
    check("interp_max", round(figures["interp_max"], 6), 1.5)
    check("now_max", round(figures["now_max"], 6), 4.5)
    check("end_max", round(figures["end_max"], 6), 9.0)
    # The band: 60 degrees reads 7 x 1.5, and 70 would read 8 x 1.5.
    check("world_now_max", round(figures["world_now_max"], 6), 10.5)
    check("world_end_max", round(figures["world_end_max"], 6), 21.0)

    manifest = ("# note declination_model=9.99\nabc  aaa.ulg  url  declination=1.00 "
                "declination_model=1.23 antenna=0\nabd  bbb.ulg  url  declination_model=none\n")
    check("pins", pins(manifest), {"aaa": 1.23})
    check("agreement", round(rust_agreement(flat, [("x/aaa.csv", 0.0, 0.0)], {"aaa": 1.23}), 6),
          1.23)
    check("no pinned site", rust_agreement(flat, [("x/zzz.csv", 0.0, 0.0)], {"aaa": 1.23}), None)

    copy = "X = 1\nDECLINATION_TABLE = (\n    (1, -2,\n     3),\n    (4, 5, 6),\n)\n"
    check("converter table", converter_table(copy), [[1, -2], [4, 5, 6]])

    for failure in failures:
        print(f"declination self-test: {failure}", file=sys.stderr)
    if failures:
        sys.exit(1)
    print("declination self-test: ok")


def main(argv):
    parser = argparse.ArgumentParser(prog="tools/declination.py",
                                     description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--self-test", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--drift", action="store_true")
    mode.add_argument("--px4", metavar="CHECKOUT")
    parser.add_argument("--model", help="with --epoch: the coefficient file, e.g. WMM_2025")
    parser.add_argument("--epoch", help="with --model: the decimal year to evaluate it at")
    parser.add_argument("--at", type=float, help="with --drift: the year for now_max")
    parser.add_argument("logs", nargs="*",
                        help="with --drift: converted logs, in place of the default sets")
    args = parser.parse_args(argv)
    if (args.model is None) != (args.epoch is None):
        parser.error("--model and --epoch go together")
    if (args.at is not None or args.logs) and not args.drift:
        parser.error("--at and logs go with --drift")
    if args.model and (args.drift or args.px4 or args.self_test):
        parser.error("--model and --epoch regenerate, or --check")
    try:
        if args.self_test:
            self_test()
        elif args.px4:
            px4(args.px4)
        elif args.drift:
            drift(args.at if args.at is not None else decimal_year(date.today()), args.logs)
        else:
            regenerate(args.model, args.epoch, args.check)
    except (ValueError, OSError) as e:
        sys.exit(f"declination: {e}")


if __name__ == "__main__":
    main(sys.argv[1:])
