#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["pygeomag==1.1.0"]
# ///
"""Generate the magnetic declination table in `src/magnetic.rs` from the World Magnetic Model.

    uv run tools/declination.py                      regenerate at the model and epoch it names
    uv run tools/declination.py --model WMM_2025 --epoch 2027.5   regenerate at another
    uv run tools/declination.py --px4 <checkout>     rebuild PX4's table, to check the generator
    uv run tools/declination.py --drift [--at <year>] [log.csv ...]   the table at the corpus
    python3 tools/declination.py --self-test         run the fixtures

The table is the model's declination every 10 degrees of latitude and longitude, at sea level, at
one epoch, in hundredths of a degree. The model is NCEI's coefficient file as `pygeomag` ships it,
checked against the sha256 below (`reference/README.md` records where NCEI publishes it); the
WMM is public domain, so the table carries no licence. The lines between the two marker comments
in `src/magnetic.rs` are this script's output and nothing else, and a run with no arguments reads
the model and epoch back from them, so regenerating at the same epoch must leave the file
byte-identical.

`--px4` is the evidence the generator is right: WMM-2020 at the epoch and scale PX4's
`geo_magnetic_tables.hpp` names reproduces PX4's `declination_table` cell for cell, a table PX4
built from NOAA's web calculator rather than from this code. A sign, an axis order or a unit
wrong here fails it.

`--drift` is when to regenerate (GOALS.md, "Magnetic declination from a table"). At every
`# Navigation origin` in the converted logs named, `data/logs/*.csv` by default, it looks the table up as `declination_at` does and
prints, in degrees, the largest difference from the model at the table's epoch (`interp_max`,
the 10-degree grid's own error), at `--at` or today (`now_max`), and at the end of the model's
five-year life (`end_max`).
"""

import glob
import hashlib
import math
import os
import re
import sys
from datetime import date

RESOLUTION = 10
LATITUDES = range(-90, 91, RESOLUTION)
LONGITUDES = range(-180, 181, RESOLUTION)

# Degrees per table unit. Fixed rather than fitted to the table's extreme, as PX4's generator does:
# 180 degrees is 18000, inside i16, and a round unit is one a reader can check by eye.
SCALE = 0.01

# sha256 of each coefficient file this script will build from, as `pygeomag` ships it. WMM_2025's
# is that of `WMM2025.COF` in NCEI's `WMM2025COF.zip`; WMM_2020 is here for `--px4` alone.
COEFFICIENTS = {
    "WMM_2025": "dfa8597825af4e0b87ff4198a5b4fb661b3c49f4cd090cd0164e0259b075582f",
    "WMM_2020": "e65453b7d2ed34ae30f6f7361aaec403e103c2abf59ee46393bd4c4f880c4fa8",
}

TARGET = "src/magnetic.rs"
BEGIN = "// BEGIN generated by tools/declination.py; edit the script, not these lines."
END = "// END generated by tools/declination.py"
PROVENANCE = re.compile(r"`(WMM_\d{4})` at epoch (\d{4}\.\d+)")


def model(name):
    """A `pygeomag.GeoMag` for one coefficient file, refused unless its sha256 is the pinned one."""
    if name not in COEFFICIENTS:
        raise ValueError(f"no pinned coefficient file for {name}; known: {', '.join(COEFFICIENTS)}")
    import pygeomag

    path = os.path.join(os.path.dirname(pygeomag.__file__), "wmm", f"{name}.COF")
    with open(path, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    if digest != COEFFICIENTS[name]:
        raise ValueError(f"{path} has sha256 {digest}, not the pinned {COEFFICIENTS[name]}")
    return pygeomag.GeoMag(coefficients_file=f"wmm/{name}.COF")


def declination(geomag, latitude, longitude, epoch):
    """The model's declination in degrees, at sea level. Past the model's life only for `--px4`,
    whose epoch PX4 chose, and `--drift`, which asks how stale the table has become."""
    return geomag.calculate(glat=latitude, glon=longitude, alt=0, time=epoch,
                            allow_date_outside_lifespan=True).d


def grid(geomag, epoch, scale):
    """The table: rows latitude -90 to 90, columns longitude -180 to 180, in units of `scale`."""
    rows = [[round(declination(geomag, lat, lon, epoch) / scale) for lon in LONGITUDES]
            for lat in LATITUDES]
    for row in rows:
        for value in row:
            if not -32768 <= value <= 32767:
                raise ValueError(f"{value} does not fit an i16 at scale {scale}")
    return rows


def wrap(values, indent, width=100):
    """Comma-separated values filling lines of at most `width` columns, as rustfmt would."""
    lines, line = [], indent
    for i, value in enumerate(values):
        item = str(value) + ("," if i < len(values) - 1 else "")
        candidate = item if line == indent else " " + item
        if line != indent and len(line) + len(candidate) > width:
            lines.append(line)
            line, candidate = indent, item
        line += candidate
    lines.append(line)
    return lines


def rust(name, epoch, rows):
    """The generated region of `src/magnetic.rs`, markers included."""
    out = [
        BEGIN,
        "",
        "/// Degrees per table unit.",
        f"const SCALE: f32 = {SCALE};",
        "",
        "/// Grid spacing in degrees, on both axes.",
        f"const RESOLUTION: f32 = {RESOLUTION:.1f};",
        "",
        f"/// The declination from `{name}` at epoch {epoch}, at sea level, in [`SCALE`] degrees.",
        "/// Rows are latitude −90° to 90°, columns longitude −180° to 180°.",
        "#[rustfmt::skip]",
        f"const TABLE: [[i16; {len(LONGITUDES)}]; {len(LATITUDES)}] = [",
    ]
    for latitude, row in zip(LATITUDES, rows):
        out += [f"    // {latitude}°", "    ["] + wrap(row, " " * 8) + ["    ],"]
    out += ["];", "", END]
    return "\n".join(out)


def region(text):
    """(before, generated, after) of a file holding exactly one generated region."""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("want exactly one BEGIN and one END marker")
    before, rest = text.split(BEGIN)
    generated, after = rest.split(END)
    return before, BEGIN + generated + END, after


def provenance(generated):
    """(model, epoch) as the generated region names them."""
    found = PROVENANCE.findall(generated)
    if len(found) != 1:
        raise ValueError("the generated region names no single model and epoch")
    return found[0][0], found[0][1]


def table_of(generated):
    """The rows of a generated region, read back as integers."""
    body = generated.split("const TABLE", 1)[1].split("= [", 1)[1]
    rows = []
    for block in body.split("    [")[1:]:
        cells = block.split("    ],")[0]
        rows.append([int(v) for v in re.findall(r"-?\d+", cells)])
    if len(rows) != len(LATITUDES) or any(len(r) != len(LONGITUDES) for r in rows):
        raise ValueError(f"table is not {len(LATITUDES)} x {len(LONGITUDES)}")
    return rows


def lookup(rows, scale, latitude, longitude):
    """`declination_at` in `src/magnetic.rs`, in f64: bilinear in the cell about the point."""
    latitude = min(max(latitude, -90.0), 90.0)
    if longitude > 180.0:
        longitude -= 360.0
    if longitude < -180.0:
        longitude += 360.0
    longitude = min(max(longitude, -180.0), 180.0)

    def cell(offset, count):
        index = min(int(offset / RESOLUTION), count - 2)
        return index, min(max(offset / RESOLUTION - index, 0.0), 1.0)

    row, north_frac = cell(latitude + 90.0, len(rows))
    column, east_frac = cell(longitude + 180.0, len(rows[0]))
    sw, se = rows[row][column], rows[row][column + 1]
    nw, ne = rows[row + 1][column], rows[row + 1][column + 1]
    south = sw + east_frac * (se - sw)
    north = nw + east_frac * (ne - nw)
    return (south + north_frac * (north - south)) * scale


def origins(paths):
    """(latitude, longitude) of each converted log's `# Navigation origin`, where it has one."""
    found = []
    for path in paths:
        with open(path) as f:
            for line in f:
                if not line.startswith("#"):
                    break
                m = re.match(r"# Navigation origin (-?[\d.]+) (-?[\d.]+) ", line)
                if m:
                    found.append((float(m.group(1)), float(m.group(2))))
    return found


def decimal_year(day):
    start = date(day.year, 1, 1)
    return day.year + (day - start).days / (date(day.year + 1, 1, 1) - start).days


def difference(a, b):
    """a - b in degrees, wrapped into [-180, 180)."""
    return (a - b + 180.0) % 360.0 - 180.0


def regenerate(name=None, epoch=None):
    with open(TARGET) as f:
        text = f.read()
    before, generated, after = region(text)
    if name is None or epoch is None:
        known_name, known_epoch = provenance(generated)
        name, epoch = name or known_name, epoch or known_epoch
    rows = grid(model(name), float(epoch), SCALE)
    with open(TARGET, "w") as f:
        f.write(before + rust(name, epoch, rows) + after)
    print(f"declination: {TARGET} from {name} at epoch {epoch}")


def px4(checkout):
    path = os.path.join(checkout, "src/lib/world_magnetic_model/geo_magnetic_tables.hpp")
    with open(path) as f:
        header = f.read()
    section = header.split("declination_table[")[0].rsplit("// Magnetic declination", 1)[1]
    name = re.search(r"Model: (WMM-\d{4})", section).group(1).replace("-", "_")
    epoch = float(re.search(r"Date: ([\d.]+)", section).group(1))
    scale = float(re.search(r"WMM_DECLINATION_SCALE_TO_DEGREES = ([\d.]+)f", header).group(1))
    body = header.split("declination_table[")[1].split("};")[0]
    want = [[int(v) for v in re.findall(r"-?\d+", line.split("*/")[1])]
            for line in body.splitlines() if "LAT:" in line]
    got = grid(model(name), epoch, scale)
    cells = [(lat, lon, g, w) for lat, gr, wr in zip(LATITUDES, got, want)
             for lon, g, w in zip(LONGITUDES, gr, wr) if g != w]
    count = len(LATITUDES) * len(LONGITUDES)
    print(f"px4 model={name} epoch={epoch} scale={scale} cells={count} differ={len(cells)}")
    for lat, lon, g, w in cells[:10]:
        print(f"  {lat} {lon}: {g} against PX4's {w}")
    if cells:
        sys.exit(1)


def drift(at, paths):
    with open(TARGET) as f:
        generated = region(f.read())[1]
    name, epoch = provenance(generated)
    rows = table_of(generated)
    sites = origins(paths or [p for p in sorted(glob.glob("data/logs/*.csv")) if ".replay" not in p])
    if not sites:
        sys.exit("declination: no `# Navigation origin` in the logs; fetch and convert first")
    geomag = model(name)
    end = int(name.split("_")[1]) + 5.0

    def worst(when):
        return max(abs(difference(lookup(rows, SCALE, lat, lon),
                                  declination(geomag, lat, lon, when))) for lat, lon in sites)

    print(f"drift model={name} epoch={epoch} at={at:.2f} origins={len(sites)} "
          f"interp_max={worst(float(epoch)):.2f} now_max={worst(at):.2f} "
          f"end_max={worst(end):.2f} end={end:.1f}")


def self_test():
    failures = []

    def check(name, got, want):
        if got != want:
            failures.append(f"{name}: got {got!r}, want {want!r}")

    def refused(name, call):
        try:
            call()
            failures.append(f"{name}: accepted")
        except ValueError:
            pass

    # A fake grid whose value is 100 * row + column, so the corner a lookup reads is legible.
    rows = [[100 * i + j for j in range(len(LONGITUDES))] for i in range(len(LATITUDES))]
    text = "head\n" + rust("WMM_2025", "2027.5", rows) + "\ntail\n"
    before, generated, after = region(text)
    check("region before", before, "head\n")
    check("region after", after, "\ntail\n")
    check("provenance", provenance(generated), ("WMM_2025", "2027.5"))
    # Survives a reader that drops the first or last cell of a row, or a row: the read-back is
    # compared whole against the grid it was written from.
    check("read back", table_of(generated), rows)
    check("round trip", rust("WMM_2025", "2027.5", table_of(generated)), generated)
    # Unpacking the split refuses both of these too, so removing the count check survives
    # them: it is there for the message.
    refused("two regions", lambda: region(text + text))
    refused("no region", lambda: region("nothing"))
    refused("a short row", lambda: table_of(generated.replace("        0, 1, 2,", "        1, 2,", 1)))

    # Wrapping: no line past 100 columns, a full line before the break, no comma on the last.
    values = list(range(-20000, -19963))
    lines = wrap(values, " " * 8)
    first = len(re.findall(r"-?\d+", lines[0]))
    check("wrap width", max(len(line) for line in lines) <= 100, True)
    check("wrap full", len(f"{lines[0]} {values[first]},") > 100, True)
    check("wrap last comma", lines[-1].endswith(","), False)
    check("wrap all values", sum(len(re.findall(r"-?\d+", line)) for line in lines), 37)

    # The lookup, against corners chosen to tell rows from columns. At (-90, -180) the cell's
    # south-west corner is 0; one step north is 100, one step east 1.
    check("corner", lookup(rows, 1.0, -90.0, -180.0), 0.0)
    check("north", lookup(rows, 1.0, -80.0, -180.0), 100.0)
    check("east", lookup(rows, 1.0, -90.0, -170.0), 1.0)
    check("inside", lookup(rows, 1.0, -85.0, -177.5), 50.25)
    check("last row and column", lookup(rows, 1.0, 90.0, 180.0), 1836.0)
    check("wraps", lookup(rows, 1.0, 0.0, 190.0), lookup(rows, 1.0, 0.0, -170.0))
    check("clamps", lookup(rows, 1.0, 95.0, 20.0), lookup(rows, 1.0, 90.0, 20.0))
    check("scale", lookup(rows, 0.01, -80.0, -180.0), 1.0)

    check("difference wraps", difference(179.0, -179.0), -2.0)
    check("decimal year", decimal_year(date(2027, 7, 2)), 2027 + 182 / 365)
    refused("an unpinned model", lambda: model("WMM_1990"))

    for failure in failures:
        print(f"declination self-test: {failure}", file=sys.stderr)
    if failures:
        sys.exit(1)
    print("declination self-test: ok")


def main(argv):
    if argv == ["--self-test"]:
        self_test()
        return
    try:
        if argv[:1] == ["--px4"] and len(argv) == 2:
            px4(argv[1])
        elif argv[:1] == ["--drift"]:
            at, paths = decimal_year(date.today()), argv[1:]
            if paths[:1] == ["--at"] and len(paths) >= 2:
                at, paths = float(paths[1]), paths[2:]
            drift(at, paths)
        elif argv[:1] == ["--model"] and len(argv) == 4 and argv[2] == "--epoch":
            regenerate(argv[1], argv[3])
        elif not argv:
            regenerate()
        else:
            sys.exit(__doc__.split("\n\n")[1])
    except ValueError as e:
        sys.exit(f"declination: {e}")


if __name__ == "__main__":
    main(sys.argv[1:])
