#!/usr/bin/env python3
"""Draw and render the validation pages from their templates and the runs tools/validation.sh captured.

    tools/validation.py draw <src> <runs> <root>      draw every figure a page places, in parallel
    tools/validation.py render <src> <runs> <root>    write the pages; print each path written
    tools/validation.py check <src> <runs> <root>     fail if the committed pages or figures differ
    tools/validation.py --self-test                   run the fixtures

A page under `validation/src/` is Markdown with placeholders, and every number and figure on
the published page comes through one of them, so no figure is typed by hand and each names the
run that produced it:

    {{score mission pos_h}}            a key off that scenario's `score` line
    {{summary mission recovered}}      ... its `summary` line
    {{anees gnss_latency any_pos}}     ... its `anees` line, data/anees.sh's ensemble
    {{agreement 89a498ce/raw climb}}   ... a corpus log's `agreement` line, per R policy
    {{summary 89a498ce/raw rate}}      a corpus run's `summary` line
    {{seed mission}}                   the seed data/scenarios.txt pins for that scenario
    {{count scenarios}}                how many runs a list names (lists below)
    {{table score mission,static pos_h,pos_v}}   one row per run, one column per key
    {{figure mission error_position}}  a figure tools/replay_report.py drew, with its caption
    {{stamp}}                          the commit the runs were produced at

A scenario run is named as in data/scenarios.txt; a corpus run as a prefix of the log's name and
the policy, `89a498ce/raw`, and a prefix naming two logs is refused. Where a table or a count
covers every run, it names a list rather than spelling the runs out, so a scenario or log added
to the gates reaches the page without an edit here: `@scenarios` is data/scenarios.txt,
`@anees` data/anees.txt, and `@corpus/raw` or `@corpus/px4` every data/manifest.txt log under
that policy, each in its file's order.

A placeholder naming a run, key or figure that does not exist is refused rather than rendered
empty, and so is a `{{` left in the page because it was malformed: a missing key is how a
renamed `score` key would otherwise publish a blank cell, the failure data/expect.sh refuses on
the gates for the same reason.

This computes nothing. It copies values off lines the harness, tools/anees.py and
tools/agreement.py printed (AGENTS.md, "One statistic, one implementation"), and lays them out;
figures are tools/replay_report.py's, which `draw` only invokes. It owns where each run's files
are, so that nothing else resolves a run's name to a directory. Standard library only.
"""

import difflib
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

PLACEHOLDER = re.compile(r"\{\{\s*([a-z]+)((?:\s+[^\s}]+)*)\s*\}\}")
STAMP = "Generated by `tools/validation.sh` at"


def pairs(line):
    """`{key: value}` for the `key=value` tokens of one printed line."""
    return dict(token.split("=", 1) for token in line.split() if "=" in token)


def first_fields(path):
    """The first field of every line of a gate file that is not a comment."""
    fields = []
    for line in Path(path).read_text().splitlines():
        words = line.split()
        if words and not words[0].startswith("#"):
            fields.append(words)
    return fields


def figures(src):
    """`{run: [slug, ...]}` for every `{{figure}}` placeholder under `src`, in page order."""
    wanted = {}
    for page in sorted(Path(src).glob("*.md")):
        for kind, rest in PLACEHOLDER.findall(page.read_text()):
            if kind != "figure":
                continue
            run, slug = rest.split()
            slugs = wanted.setdefault(run, [])
            if slug not in slugs:
                slugs.append(slug)
    return wanted


def run_dir(run):
    """A run's figure directory: a scenario by name, a corpus run as `<log>-<policy>`."""
    return run.replace("/", "-")


class Runs:
    """What tools/validation.sh captured, and where each run's files are.

    `<runs>/sim/<name>/` holds a scenario's log, truth and replay, `<runs>/scenarios/<name>.out`
    its stdout, `<runs>/anees/<name>.{anees,csv}` its ensemble, `<runs>/compare/` what
    data/fetch.sh --compare wrote, `<runs>/figures/<run>/<slug>.{png,md}` a figure and its
    caption, and `<runs>/commit` the build.
    """

    def __init__(self, runs, root):
        self.runs, self.root = Path(runs), Path(root)
        commit = self.runs / "commit"
        self.commit = commit.read_text().strip() if commit.exists() else "unknown"
        scenarios = first_fields(self.root / "data/scenarios.txt")
        self.seeds = {words[0]: words[1] for words in scenarios}
        self.lists = {
            "@scenarios": [words[0] for words in scenarios],
            "@anees": [words[0] for words in first_fields(self.root / "data/anees.txt")],
        }
        logs = [words[1].removesuffix(".ulg")
                for words in first_fields(self.root / "data/manifest.txt")]
        for policy in ("raw", "px4"):
            self.lists[f"@corpus/{policy}"] = [f"{log[:8]}/{policy}" for log in logs]
        self.agreement = {}
        agreement = self.runs / "compare/agreement.txt"
        if agreement.exists():
            for line in agreement.read_text().splitlines():
                keys = pairs(line)
                self.agreement[(keys["log"], keys["r_policy"])] = keys

    def names(self, spec):
        """The runs a table or count names: a list, or runs separated by commas."""
        if spec.startswith("@"):
            if spec not in self.lists:
                raise ValueError(f"`{spec}` is not a list; have {', '.join(self.lists)}")
            return self.lists[spec]
        return spec.split(",")

    def log_dir(self, run):
        """The one `compare/<log>` directory a corpus run's prefix names."""
        log, _policy = run.split("/")
        matches = sorted(p for p in (self.runs / "compare").glob(f"{log}*") if p.is_dir())
        if len(matches) != 1:
            raise ValueError(f"`{run}` names {len(matches)} corpus logs, not one")
        return matches[0]

    def line(self, kind, run):
        """The keys of one printed line, or ValueError naming what is missing."""
        if kind == "agreement":
            key = (self.log_dir(run).name, run.split("/")[1])
            if key not in self.agreement:
                raise ValueError(f"no agreement line for `{run}`")
            return self.agreement[key]
        if kind == "anees":
            path = self.runs / "anees" / f"{run}.anees"
        elif "/" in run:
            path = self.log_dir(run) / f"{run.split('/')[1]}.summary"
        else:
            path = self.runs / "scenarios" / f"{run}.out"
        if not path.exists():
            raise ValueError(f"no {kind} for `{run}`: {path} is missing")
        for line in path.read_text().splitlines():
            if line.startswith(f"{kind} "):
                return pairs(line)
        raise ValueError(f"{path} carries no `{kind}` line")

    def value(self, kind, run, key):
        keys = self.line(kind, run)
        if key not in keys:
            raise ValueError(f"`{run}`'s {kind} line has no `{key}`")
        return keys[key]

    def draw_command(self, run, slugs):
        """The tools/replay_report.py invocation that draws `slugs` for `run`."""
        out = ["--figures", str(self.runs / "figures" / run_dir(run)), "--only", ",".join(slugs)]
        if "/" in run:
            log, policy = self.log_dir(run), run.split("/")[1]
            files = [log / "input.csv", log / f"{policy}.csv",
                     "--reference", log / "reference.csv", "--summary", log / f"{policy}.summary"]
        else:
            if run not in self.seeds:
                raise ValueError(f"a page draws `{run}`, which is no scenario")
            sim = self.runs / "sim" / run
            files = [sim / f"{run}.csv", sim / "replay.csv", sim / f"{run}.truth.csv",
                     "--summary", self.runs / "scenarios" / f"{run}.out"]
            ensemble = self.runs / "anees" / f"{run}.csv"
            if ensemble.exists():
                files += ["--anees", ensemble]
        return (["uv", "run", "--quiet", str(self.root / "tools/replay_report.py")]
                + [str(f) for f in files] + out)


def relative(page, target):
    """`target` as a link from `page`, both relative to the repository root."""
    return os.path.relpath(target, Path(page).parent).replace(os.sep, "/")


def expand(kind, args, runs, page):
    """The Markdown one placeholder stands for."""
    if kind in ("score", "summary", "anees", "agreement") and len(args) == 2:
        return runs.value(kind, *args)
    if kind == "seed" and len(args) == 1:
        if args[0] not in runs.seeds:
            raise ValueError(f"no seed for `{args[0]}` in data/scenarios.txt")
        return runs.seeds[args[0]]
    if kind == "count" and len(args) == 1:
        return str(len(runs.names(args[0])))
    if kind == "table" and len(args) == 3:
        source, names, keys = args[0], runs.names(args[1]), args[2].split(",")
        seeded = source in ("score", "summary") and all(n in runs.seeds for n in names)
        head = ["run"] + (["seed"] if seeded else []) + [f"`{k}`" for k in keys]
        rows = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        for name in names:
            cells = [f"`{name}`"] + ([runs.seeds[name]] if seeded else [])
            cells += [runs.value(source, name, key) for key in keys]
            rows.append("| " + " | ".join(cells) + " |")
        return "\n".join(rows)
    if kind == "figure" and len(args) == 2:
        run, slug = args
        caption = runs.runs / "figures" / run_dir(run) / f"{slug}.md"
        if not caption.exists():
            raise ValueError(f"no figure `{slug}` for `{run}`: {caption} is missing")
        image = relative(page, f"validation/figures/{run_dir(run)}/{slug}.png")
        return f"![{slug} for {run}]({image})\n\n{caption.read_text().strip()}"
    if kind == "stamp" and not args:
        return (f"{STAMP} `{runs.commit}`; every figure on this page is from that build, "
                "and `tools/validation.sh --check` re-derives them.")
    raise ValueError(f"`{{{{{kind} {' '.join(args)}}}}}` is not a placeholder this renders")


def published(src_page):
    """Where a template is published: `VALIDATION.md` at the root, the rest under validation/."""
    name = Path(src_page).name
    return Path(name) if name == "VALIDATION.md" else Path("validation") / name


def render(text, runs, page):
    """`text` with every placeholder expanded, or ValueError naming each that failed."""
    problems = []

    def substitute(match):
        try:
            return expand(match.group(1), match.group(2).split(), runs, page)
        except ValueError as e:
            problems.append(str(e))
            return ""

    body = PLACEHOLDER.sub(substitute, text)
    # What PLACEHOLDER did not match is a typo -- a capital, a missing brace -- and would
    # otherwise be published as it stands.
    problems += [f"malformed placeholder `{m.group(0)}`"
                 for m in re.finditer(r"\{\{[^\n]{0,60}|[^\n]{0,60}\}\}", body)]
    if problems:
        raise ValueError(f"{page}:\n  - " + "\n  - ".join(problems))
    source = Path("validation/src") / Path(page).name
    return (f"<!-- Generated from {source} by tools/validation.sh; edit that, not this. -->\n"
            + body)


def render_all(src, runs):
    """`{published path: text}` for every template under `src`."""
    return {published(p): render(p.read_text(), runs, str(published(p)))
            for p in sorted(Path(src).glob("*.md"))}


def draw(src, runs, jobs):
    """Run every figure's tools/replay_report.py at once, `jobs` at a time.

    Each is a separate process reading its own run, so they share nothing; drawn in turn
    they were 80 of validation.sh's 186 s. A failure prints the tool's own reason, which is
    the guard that refused, rather than only that it failed.
    """
    commands = [(run, runs.draw_command(run, slugs)) for run, slugs in figures(src).items()]

    def one(item):
        run, command = item
        done = subprocess.run(command, capture_output=True, text=True)
        return run, done.returncode, done.stderr

    failed = []
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        for run, status, stderr in pool.map(one, commands):
            if status != 0:
                failed.append(f"{run}:\n{stderr.strip()}")
    if failed:
        raise ValueError("tools/replay_report.py failed for\n" + "\n".join(failed))


def without_stamp(text):
    return [line for line in text.splitlines() if not line.startswith(STAMP)]


def check(src, runs, root):
    """Every difference between what is committed and what this build renders, as messages.

    Text is compared, the stamp aside; figures are checked present and nothing more, since
    matplotlib's PNG bytes are not stable across builds. Orphans count too: a page no template
    produces, or a figure no page places, is stale evidence that reads as current.
    """
    root, problems = Path(root), []
    pages = render_all(src, runs)
    for path, text in pages.items():
        committed = root / path
        if not committed.exists():
            problems.append(f"{path}: not committed")
            continue
        diff = list(difflib.unified_diff(without_stamp(committed.read_text()),
                                         without_stamp(text), str(path), "rendered",
                                         lineterm=""))
        if diff:
            problems.append("\n".join(diff))
    written = {Path(p) for p in pages}
    for page in sorted([Path("VALIDATION.md")] + [p.relative_to(root)
                       for p in (root / "validation").glob("*.md")]):
        if page not in written and page.name != "README.md" and (root / page).exists():
            problems.append(f"{page}: committed, but no template produces it")
    wanted = {Path("validation/figures") / run_dir(run) / f"{slug}.png"
              for run, slugs in figures(src).items() for slug in slugs}
    have = {p.relative_to(root) for p in (root / "validation/figures").glob("*/*.png")}
    problems += [f"{p}: placed on a page, not committed" for p in sorted(wanted - have)]
    problems += [f"{p}: committed, placed on no page" for p in sorted(have - wanted)]
    return problems


def self_test():
    import tempfile

    failures = []

    def expect(name, got, want):
        if got != want:
            failures.append(f"{name}: got {got!r}, want {want!r}")

    def refused(name, action):
        try:
            action()
            failures.append(f"{name}: accepted")
        except ValueError:
            pass

    with tempfile.TemporaryDirectory() as tmp:
        root, out = Path(tmp) / "repo", Path(tmp) / "runs"
        (root / "data").mkdir(parents=True)
        (root / "data/scenarios.txt").write_text("# header\nmission 2 pos_h<=1\nstatic 1 x\n")
        (root / "data/anees.txt").write_text("# header\nmission 50 runs=50\n")
        (root / "data/manifest.txt").write_text(
            "# header\nabc 89a498ce-9aa1.ulg https://x rate=1\n")
        (out / "scenarios").mkdir(parents=True)
        (out / "scenarios/mission.out").write_text(
            "noise\nsummary epochs=10 recovered=0\nscore pos_h=0.244 pos_h_max=0.8\n")
        (out / "scenarios/static.out").write_text("score pos_h=0.5\n")
        (out / "anees").mkdir()
        (out / "anees/mission.anees").write_text("anees mission runs=50 any_pos=0\n")
        (out / "compare/89a498ce-9aa1/").mkdir(parents=True)
        (out / "compare/89a498ce-9aa1/raw.summary").write_text("summary rate=250\n")
        (out / "compare/agreement.txt").write_text(
            "agreement log=89a498ce-9aa1 r_policy=raw climb=-1.5\n")
        (out / "figures/mission").mkdir(parents=True)
        (out / "figures/mission/error_position.md").write_text("Position error.\n")
        (out / "commit").write_text("abc1234\n")
        runs = Runs(out, root)

        def rendered(text, page="validation/accuracy.md"):
            return render(text, runs, page).split("\n", 1)[1]

        expect("score", rendered("{{score mission pos_h}}"), "0.244")
        # A prefix of another key is not that key: `pos_h` is not read off `pos_h_max`.
        expect("exact key", rendered("{{score mission pos_h_max}}"), "0.8")
        expect("summary", rendered("{{summary mission recovered}}"), "0")
        expect("anees", rendered("{{anees mission any_pos}}"), "0")
        expect("agreement", rendered("{{agreement 89a498ce/raw climb}}"), "-1.5")
        expect("corpus summary", rendered("{{summary 89a498ce/raw rate}}"), "250")
        expect("seed", rendered("{{seed mission}}"), "2")
        expect("count of a list", rendered("{{count @scenarios}}"), "2")
        expect("count of the corpus", rendered("{{count @corpus/raw}}"), "1")
        expect("table", rendered("{{table score mission pos_h}}"),
               "| run | seed | `pos_h` |\n|---|---|---|\n| `mission` | 2 | 0.244 |")
        # A list is every run in its gate file, in that file's order.
        expect("table over a list", rendered("{{table score @scenarios pos_h}}"),
               "| run | seed | `pos_h` |\n|---|---|---|\n| `mission` | 2 | 0.244 |\n"
               "| `static` | 1 | 0.5 |")
        expect("figure from a page under validation/", rendered(
            "{{figure mission error_position}}"),
            "![error_position for mission](figures/mission/error_position.png)"
            "\n\nPosition error.")
        expect("figure from the root page", rendered(
            "{{figure mission error_position}}", page="VALIDATION.md"),
            "![error_position for mission](validation/figures/mission/error_position.png)"
            "\n\nPosition error.")
        expect("stamp", rendered("{{stamp}}").startswith(f"{STAMP} `abc1234`"), True)
        expect("header", render("x", runs, "validation/accuracy.md").splitlines()[0],
               "<!-- Generated from validation/src/accuracy.md by tools/validation.sh; "
               "edit that, not this. -->")
        expect("draw command", runs.draw_command("mission", ["a", "b"])[-4:],
               ["--figures", str(out / "figures/mission"), "--only", "a,b"])
        expect("corpus draw command", runs.draw_command("89a498ce/raw", ["track"])[4],
               str(out / "compare/89a498ce-9aa1/input.csv"))

        for name, text in [
            ("a missing key", "{{score mission pos_q}}"),
            ("a missing run", "{{score hover pos_h}}"),
            ("a missing figure", "{{figure mission error_velocity}}"),
            ("an unknown kind", "{{median mission pos_h}}"),
            ("an unknown list", "{{count @logs}}"),
            ("a line the file lacks", "{{agreement 00000000/raw climb}}"),
            ("a capital", "{{Score mission pos_h}}"),
            ("a missing brace", "{{score mission pos_h}"),
            ("a kind with a dash", "{{ score-x mission }}"),
        ]:
            refused(name, lambda text=text: render(text, runs, "validation/accuracy.md"))
        refused("drawing no scenario", lambda: runs.draw_command("hover", ["a"]))

        # Committed state against what renders: a page that differs past its stamp, an orphaned
        # page, a figure placed and missing, and one committed and placed nowhere.
        src = Path(tmp) / "src"
        src.mkdir()
        (src / "accuracy.md").write_text("{{stamp}}\n{{score mission pos_h}}\n"
                                         "{{figure mission error_position}}\n")
        (root / "validation/figures/mission").mkdir(parents=True)
        (root / "validation/figures/mission/error_position.png").write_bytes(b"")
        page = render_all(src, runs)[Path("validation/accuracy.md")]
        (root / "validation/accuracy.md").write_text(
            page.replace("abc1234", "0000000"))
        expect("current", check(src, runs, root), [])
        (root / "validation/accuracy.md").write_text(page.replace("0.244", "0.281"))
        expect("a stale number", len(check(src, runs, root)), 1)
        (root / "validation/accuracy.md").write_text(page)
        (root / "validation/old.md").write_text("x")
        (root / "validation/README.md").write_text("x")
        (root / "validation/figures/mission/anees.png").write_bytes(b"")
        (root / "validation/figures/mission/error_position.png").unlink()
        expect("orphans and a missing figure", sorted(check(src, runs, root)), [
            "validation/figures/mission/anees.png: committed, placed on no page",
            "validation/figures/mission/error_position.png: placed on a page, not committed",
            "validation/old.md: committed, but no template produces it"])

        # Two logs sharing the prefix a page names: refused rather than read from whichever
        # sorts first, for a summary and for an agreement line alike.
        (out / "compare/89a498ce-ffff").mkdir()
        (out / "compare/89a498ce-ffff/raw.summary").write_text("summary rate=50\n")
        refused("an ambiguous corpus run", lambda: render(
            "{{summary 89a498ce/raw rate}}", runs, "validation/ekf2.md"))
        refused("an ambiguous agreement run", lambda: render(
            "{{agreement 89a498ce/raw climb}}", runs, "validation/ekf2.md"))

    for failure in failures:
        print(f"validation self-test: {failure}", file=sys.stderr)
    if failures:
        sys.exit(1)
    print("validation self-test: ok")


def main(argv):
    if argv == ["--self-test"]:
        self_test()
        return
    if len(argv) != 4 or argv[0] not in ("draw", "render", "check"):
        sys.exit(__doc__.split("\n\n")[1])
    command, src, runs_dir, root = argv[0], Path(argv[1]), argv[2], Path(argv[3])
    try:
        runs = Runs(runs_dir, root)
        if command == "draw":
            draw(src, runs, os.cpu_count() or 4)
        elif command == "check":
            problems = check(src, runs, root)
            for problem in problems:
                print(problem, file=sys.stderr)
            if problems:
                sys.exit("validation: the committed pages are not what this build renders")
            print("validation: pages current")
        else:
            for path, text in render_all(src, runs).items():
                (root / path).parent.mkdir(parents=True, exist_ok=True)
                (root / path).write_text(text)
                print(path)
    except ValueError as e:
        sys.exit(f"validation: {e}")


if __name__ == "__main__":
    main(sys.argv[1:])
