#!/usr/bin/env python3
"""Render the validation pages from their templates and the runs tools/validation.sh captured.

    tools/validation.py figures <src>                 print `<run> <slug,slug>` per run a page draws
    tools/validation.py render <src> <runs> <root>    write the pages; print each path written
    tools/validation.py --self-test                   run the fixtures

A page under `validation/src/` is Markdown with placeholders, and every number and figure on
the published page comes through one of them, so no figure is typed by hand and each names the
run that produced it:

    {{score mission pos_h}}            a key off that scenario's `score` line
    {{summary mission recovered}}      ... its `summary` line
    {{anees gnss_latency any_pos}}     ... its `anees` line, data/anees.sh's ensemble
    {{agreement 89a498ce/raw climb}}   ... a corpus log's `agreement` line, per R policy
    {{summary 89a498ce/raw rate}}      a corpus run's `summary` line
    {{seed mission}}                   the seed data/scenarios.txt pins for that scenario
    {{table score mission,static pos_h,pos_v}}   one row per run, one column per key
    {{figure mission error_position}}  a figure tools/replay_report.py drew, with its caption
    {{stamp}}                          the commit the runs were produced at

A scenario run is named as in data/scenarios.txt; a corpus run as `<first 8 of the log>/<policy>`.
A placeholder naming a run, key or figure that does not exist is refused rather than rendered
empty: a missing key is how a renamed `score` key would otherwise publish a blank cell, the
failure data/expect.sh refuses on the gates for the same reason.

This computes nothing. It copies values off lines the harness, tools/anees.py and
tools/agreement.py printed (AGENTS.md, "One statistic, one implementation"), and lays them out.
Standard library only, like tools/anees.py: it reads captured text and nothing else.
"""

import os
import re
import sys
from pathlib import Path

PLACEHOLDER = re.compile(r"\{\{\s*([a-z]+)((?:\s+[^\s}]+)*)\s*\}\}")
STAMP = "Generated by `tools/validation.sh` at"


def pairs(line):
    """`{key: value}` for the `key=value` tokens of one printed line."""
    return dict(token.split("=", 1) for token in line.split() if "=" in token)


def figures(src):
    """`{run: [slug, ...]}` for every `{{figure}}` placeholder under `src`, in page order."""
    wanted = {}
    for page in sorted(Path(src).glob("*.md")):
        for kind, rest in PLACEHOLDER.findall(page.read_text()):
            if kind != "figure":
                continue
            run, slug = rest.split()
            slugs = wanted.setdefault(run, [])
            if slug not in slugs:
                slugs.append(slug)
    return wanted


def run_dir(run):
    """Where a run's files live: a scenario by name, a corpus run as `<log>-<policy>`."""
    return run.replace("/", "-")


class Runs:
    """What tools/validation.sh captured, read once.

    `<runs>/scenarios/<name>.out` is a scenario replay's stdout, `<runs>/anees/<name>.anees` its
    ensemble line, `<runs>/compare/agreement.txt` and `<runs>/compare/<log>/<policy>.summary`
    the corpus, `<runs>/figures/<run>/<slug>.md` a caption, and `<runs>/commit` the build.
    """

    def __init__(self, runs, root):
        self.runs, self.root = Path(runs), Path(root)
        self.commit = (self.runs / "commit").read_text().strip()
        self.seeds = {}
        for line in (self.root / "data/scenarios.txt").read_text().splitlines():
            fields = line.split()
            if fields and not fields[0].startswith("#"):
                self.seeds[fields[0]] = fields[1]
        self.agreement = {}
        agreement = self.runs / "compare/agreement.txt"
        if agreement.exists():
            for line in agreement.read_text().splitlines():
                keys = pairs(line)
                self.agreement[f"{keys['log'][:8]}/{keys['r_policy']}"] = keys

    def line(self, kind, run):
        """The keys of one printed line, or ValueError naming what is missing."""
        if kind == "agreement":
            if run not in self.agreement:
                raise ValueError(f"no agreement line for `{run}`")
            return self.agreement[run]
        if kind == "anees":
            path = self.runs / "anees" / f"{run}.anees"
        elif "/" in run:
            log, policy = run.split("/")
            matches = sorted((self.runs / "compare").glob(f"{log}*/{policy}.summary"))
            if len(matches) != 1:
                raise ValueError(f"`{run}` names {len(matches)} corpus runs, not one")
            path = matches[0]
        else:
            path = self.runs / "scenarios" / f"{run}.out"
        if not path.exists():
            raise ValueError(f"no {kind} for `{run}`: {path} is missing")
        for line in path.read_text().splitlines():
            if line.startswith(f"{kind} "):
                return pairs(line)
        raise ValueError(f"{path} carries no `{kind}` line")

    def value(self, kind, run, key):
        keys = self.line(kind, run)
        if key not in keys:
            raise ValueError(f"`{run}`'s {kind} line has no `{key}`")
        return keys[key]


def relative(page, target):
    """`target` as a link from `page`, both relative to the repository root."""
    return os.path.relpath(target, Path(page).parent).replace(os.sep, "/")


def expand(kind, args, runs, page):
    """The Markdown one placeholder stands for."""
    if kind in ("score", "summary", "anees", "agreement") and len(args) == 2:
        return runs.value(kind, *args)
    if kind == "seed" and len(args) == 1:
        if args[0] not in runs.seeds:
            raise ValueError(f"no seed for `{args[0]}` in data/scenarios.txt")
        return runs.seeds[args[0]]
    if kind == "table" and len(args) == 3:
        source, names, keys = args[0], args[1].split(","), args[2].split(",")
        seeded = source in ("score", "summary") and all(n in runs.seeds for n in names)
        head = ["run"] + (["seed"] if seeded else []) + [f"`{k}`" for k in keys]
        rows = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        for name in names:
            cells = [f"`{name}`"] + ([runs.seeds[name]] if seeded else [])
            cells += [runs.value(source, name, key) for key in keys]
            rows.append("| " + " | ".join(cells) + " |")
        return "\n".join(rows)
    if kind == "figure" and len(args) == 2:
        run, slug = args
        caption = runs.runs / "figures" / run_dir(run) / f"{slug}.md"
        if not caption.exists():
            raise ValueError(f"no figure `{slug}` for `{run}`: {caption} is missing")
        image = relative(page, f"validation/figures/{run_dir(run)}/{slug}.png")
        return f"![{slug} for {run}]({image})\n\n{caption.read_text().strip()}"
    if kind == "stamp" and not args:
        return (f"{STAMP} `{runs.commit}`; every figure on this page is from that build, "
                "and `tools/validation.sh --check` re-derives them.")
    raise ValueError(f"`{{{{{kind} {' '.join(args)}}}}}` is not a placeholder this renders")


def published(src_page):
    """Where a template is published: `VALIDATION.md` at the root, the rest under validation/."""
    name = Path(src_page).name
    return Path(name) if name == "VALIDATION.md" else Path("validation") / name


def render(text, runs, page):
    """`text` with every placeholder expanded, or ValueError naming each that failed."""
    problems = []

    def substitute(match):
        try:
            return expand(match.group(1), match.group(2).split(), runs, page)
        except ValueError as e:
            problems.append(str(e))
            return ""

    body = PLACEHOLDER.sub(substitute, text)
    if problems:
        raise ValueError(f"{page}:\n  - " + "\n  - ".join(problems))
    source = Path("validation/src") / Path(page).name
    return (f"<!-- Generated from {source} by tools/validation.sh; edit that, not this. -->\n"
            + body)


def self_test():
    import tempfile

    failures = []

    def check(name, got, want):
        if got != want:
            failures.append(f"{name}: got {got!r}, want {want!r}")

    with tempfile.TemporaryDirectory() as tmp:
        root, out = Path(tmp) / "repo", Path(tmp) / "runs"
        (root / "data").mkdir(parents=True)
        (root / "data/scenarios.txt").write_text("# header\nmission 2 pos_h<=1\n")
        (out / "scenarios").mkdir(parents=True)
        (out / "scenarios/mission.out").write_text(
            "noise\nsummary epochs=10 recovered=0\nscore pos_h=0.244 pos_h_max=0.8\n")
        (out / "anees").mkdir()
        (out / "anees/mission.anees").write_text("anees mission runs=50 any_pos=0\n")
        (out / "compare/89a498ce-9aa1/").mkdir(parents=True)
        (out / "compare/89a498ce-9aa1/raw.summary").write_text("summary rate=250\n")
        (out / "compare/agreement.txt").write_text(
            "agreement log=89a498ce-9aa1 r_policy=raw climb=-1.5\n")
        (out / "figures/mission").mkdir(parents=True)
        (out / "figures/mission/error_position.md").write_text("Position error.\n")
        (out / "commit").write_text("abc1234\n")
        runs = Runs(out, root)

        def rendered(text, page="validation/accuracy.md"):
            return render(text, runs, page).split("\n", 1)[1]

        check("score", rendered("{{score mission pos_h}}"), "0.244")
        # A prefix of another key is not that key: `pos_h` is not read off `pos_h_max`.
        check("exact key", rendered("{{score mission pos_h_max}}"), "0.8")
        check("summary", rendered("{{summary mission recovered}}"), "0")
        check("anees", rendered("{{anees mission any_pos}}"), "0")
        check("agreement", rendered("{{agreement 89a498ce/raw climb}}"), "-1.5")
        check("corpus summary", rendered("{{summary 89a498ce/raw rate}}"), "250")
        check("seed", rendered("{{seed mission}}"), "2")
        check("table", rendered("{{table score mission pos_h}}"),
              "| run | seed | `pos_h` |\n|---|---|---|\n| `mission` | 2 | 0.244 |")
        check("figure from a page under validation/", rendered(
            "{{figure mission error_position}}"),
            "![error_position for mission](figures/mission/error_position.png)"
            "\n\nPosition error.")
        check("figure from the root page", rendered(
            "{{figure mission error_position}}", page="VALIDATION.md"),
            "![error_position for mission](validation/figures/mission/error_position.png)"
            "\n\nPosition error.")
        check("stamp", rendered("{{stamp}}").startswith(f"{STAMP} `abc1234`"), True)
        check("header", render("x", runs, "validation/accuracy.md").splitlines()[0],
              "<!-- Generated from validation/src/accuracy.md by tools/validation.sh; "
              "edit that, not this. -->")
        check("figures wanted", figures_of("{{figure mission a}} {{figure 89a498ce/raw b}}"
                                           " {{figure mission a}}"),
              {"mission": ["a"], "89a498ce/raw": ["b"]})

        for name, text in [
            ("a missing key", "{{score mission pos_q}}"),
            ("a missing run", "{{score hover pos_h}}"),
            ("a missing figure", "{{figure mission error_velocity}}"),
            ("an unknown kind", "{{median mission pos_h}}"),
            ("a line the file lacks", "{{agreement 00000000/raw climb}}"),
        ]:
            try:
                render(text, runs, "validation/accuracy.md")
                failures.append(f"{name}: rendered")
            except ValueError:
                pass

    for failure in failures:
        print(f"validation self-test: {failure}", file=sys.stderr)
    if failures:
        sys.exit(1)
    print("validation self-test: ok")


def figures_of(text):
    """`figures` over one string, for the fixtures."""
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        (Path(tmp) / "page.md").write_text(text)
        return figures(tmp)


def main(argv):
    if argv == ["--self-test"]:
        self_test()
        return
    if len(argv) == 2 and argv[0] == "figures":
        for run, slugs in figures(argv[1]).items():
            print(f"{run} {','.join(slugs)}")
        return
    if len(argv) == 4 and argv[0] == "render":
        src, runs_dir, root = Path(argv[1]), argv[2], Path(argv[3])
        try:
            runs = Runs(runs_dir, root)
            pages = {published(p): render(p.read_text(), runs, str(published(p)))
                     for p in sorted(src.glob("*.md"))}
        except ValueError as e:
            sys.exit(f"validation: {e}")
        for path, text in pages.items():
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text)
            print(path)
        return
    sys.exit(__doc__.split("\n\n")[1])


if __name__ == "__main__":
    main(sys.argv[1:])
