#!/usr/bin/env bash
#
# Regenerate the validation pages: VALIDATION.md and validation/*.md, with their figures (#123).
#
#   tools/validation.sh           replay everything, redraw the figures, rewrite the pages
#   tools/validation.sh --check   replay everything and fail if a page's text would change
#
# Local, never CI: the corpus half needs the fetched logs, pyulog and uv (GOALS.md, "Harness
# constraint"), and data/fetch.sh --compare is what runs it. Every gate the pages publish is
# asserted on the way, so a page is never drawn from a run that breached one: data/anees.sh
# gates the ensembles, fetch.sh --compare the corpus against data/ekf2.txt, and each scenario's
# `score` line is the one data/bench.sh gates in CI.
#
# The pages are templates under validation/src/, rendered by tools/validation.py, which copies
# every number off a line some tool printed and refuses a placeholder naming nothing. --check is
# the manifest's rule applied to prose: the committed pages must be what a fresh run renders,
# the `Generated by` stamp aside, since the commit it names moves with every commit. Figures are
# not compared byte for byte, because matplotlib's PNG output is not stable across builds; they
# are checked present, one per `{{figure}}` placeholder, and within the size budget below.

set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
src="$root/validation/src"
published="$root/validation/figures"

# The committed PNGs, in KiB. validation/README.md states it and points here. 5 MiB is about
# fifty figures at the report tool's size; the crate excludes validation/, so this is the
# repository's cost and never a download's.
budget=5120

die() { echo "validation: $*" >&2; exit 1; }

check=0
case "${1:-}" in
'') ;;
--check) check=1 ;;
*) die "usage: tools/validation.sh [--check]" ;;
esac

command -v uv >/dev/null || die "uv not found; tools/replay_report.py runs through it"
python3 "$root/tools/validation.py" --self-test >/dev/null || die "tools/validation.py self-test"

echo "building"
(cd "$root" && cargo build --quiet --release --example simulate --example replay) ||
    die "build failed"
target=$(cd "$root" && cargo metadata --format-version 1 --no-deps |
    python3 -c 'import json, sys; print(json.load(sys.stdin)["target_directory"])') ||
    die "cargo metadata failed"
simulate="$target/release/examples/simulate"
replay="$target/release/examples/replay"
out="$target/validation"
rm -rf "$out"
mkdir -p "$out/scenarios" "$out/figures"
git -C "$root" describe --always --dirty > "$out/commit"

# One flight per scenario, at the seed data/scenarios.txt pins: the run its ceilings are, so a
# figure on the accuracy page is the flight the CI gate measured.
echo "flying the scenarios"
while read -r name seed _ || [ -n "$name" ]; do
    case "$name" in ''|\#*) continue ;; esac
    dir="$out/sim/$name"
    mkdir -p "$dir"
    "$simulate" "$name" "$dir" --seed "$seed" >/dev/null || die "simulate $name failed"
    "$replay" "$dir/$name.csv" "$dir/replay.csv" "$dir/$name.truth.csv" \
        > "$out/scenarios/$name.out" || die "replay $name failed"
done < "$root/data/scenarios.txt"

echo "flying the ensembles"
"$root/data/anees.sh" --series "$out/anees" >/dev/null || die "data/anees.sh failed"

echo "replaying the corpus beside EKF2"
"$root/data/fetch.sh" --compare >/dev/null || die "data/fetch.sh --compare failed"
ln -s "$target/compare" "$out/compare"

echo "drawing"
while read -r run slugs; do
    figures="$out/figures/${run//\//-}"
    if [ "${run#*/}" = "$run" ]; then
        dir="$out/sim/$run"
        [ -d "$dir" ] || die "a page draws \`$run\`, which is no scenario"
        ensemble=()
        [ -f "$out/anees/$run.csv" ] && ensemble=(--anees "$out/anees/$run.csv")
        (cd "$root" && uv run --quiet tools/replay_report.py "$dir/$run.csv" "$dir/replay.csv" \
            "$dir/$run.truth.csv" --summary "$out/scenarios/$run.out" "${ensemble[@]}" \
            --figures "$figures" --only "$slugs" 2>/dev/null) ||
            die "tools/replay_report.py $run failed"
    else
        log=${run%/*} policy=${run#*/}
        dir=$(ls -d "$target/compare/$log"* 2>/dev/null) ||
            die "a page draws \`$run\`, which is no corpus log"
        [ "$(printf '%s\n' "$dir" | wc -l)" -eq 1 ] || die "\`$log\` names more than one log"
        (cd "$root" && uv run --quiet tools/replay_report.py "$dir/input.csv" \
            "$dir/$policy.csv" --reference "$dir/reference.csv" \
            --summary "$dir/$policy.summary" --figures "$figures" --only "$slugs" 2>/dev/null) ||
            die "tools/replay_report.py $run failed"
    fi
done < <(python3 "$root/tools/validation.py" figures "$src")

if [ "$check" = 1 ]; then
    # Rendered into a scratch root that sees the real data/, then compared page by page.
    scratch="$out/check"
    mkdir -p "$scratch"
    ln -s "$root/data" "$scratch/data"
    python3 "$root/tools/validation.py" render "$src" "$out" "$scratch" >/dev/null ||
        die "rendering failed"
    failed=0
    while read -r page; do
        if ! diff -u <(grep -v "Generated by \`tools/validation.sh\` at" "$root/$page") \
            <(grep -v "Generated by \`tools/validation.sh\` at" "$scratch/$page") >&2; then
            echo "  STALE    $page" >&2
            failed=1
        else
            echo "  ok       $page"
        fi
    done < <(cd "$scratch" && find VALIDATION.md validation -name '*.md' | sort)
    while read -r run slugs; do
        for slug in ${slugs//,/ }; do
            [ -f "$published/${run//\//-}/$slug.png" ] ||
                { echo "  MISSING  figures/${run//\//-}/$slug.png" >&2; failed=1; }
        done
    done < <(python3 "$root/tools/validation.py" figures "$src")
    [ "$failed" = 0 ] || die "the committed pages are not what this build renders"
    echo "validation: pages current"
    exit 0
fi

rm -rf "$published"
while read -r png; do
    mkdir -p "$published/$(dirname "$png")"
    cp "$out/figures/$png" "$published/$png"
done < <(cd "$out/figures" && find . -name '*.png' | sed 's|^\./||')
python3 "$root/tools/validation.py" render "$src" "$out" "$root" || die "rendering failed"
size=$(du -sk "$published" | cut -f1)
[ "$size" -le "$budget" ] || die "figures are ${size} KiB, over the ${budget} KiB budget"
echo "validation: pages written, figures ${size} of ${budget} KiB"
